- williamyeh.oracle-java
# - src: git+https://richtmat@bitbucket.org/finderbox/fb-jenkins-ci.git
- src: geerlingguy.packer-debian
- src: franklinkim.users-oh-my-zsh
- cmprescott.chrome
- geerlingguy.nodejs
- ANXS.postgresql